name: Build Windows Executable



jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --name doctor --add-data "modules;modules" --add-data "config.yaml;." main.py

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/doctor.exe
